version: "3"

services:
  chirpstack-network-server:
    image: mathieudv/chirpstack-network-server:0
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server

  chirpstack-application-server:
    image: mathieudv/chirpstack-application-server:3-kafka
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server

  chirpstack-gateway-bridge:
    image: mathieudv/chirpstack-gateway-bridge:0
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge

  chirpstack-geolocation-server:
    image: mathieudv/chirpstack-geolocation-server:0
    volumes:
      - ./configuration/chirpstack-geolocation-server:/etc/chirpstack-geolocation-server

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883

  zookeeper:
    image: zookeeper:3.5.7
    ports: 
      - 2181:2181 

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    depends_on:
      - "zookeeper"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181

volumes:
  postgresqldata:
  redisdata:
