# See https://www.chirpstack.io/geolocation-server/install/config/ for a full
# configuration example and documentation.

[geo_server.backend]
name="willy"

[geo_server.backend.willy]
# Collos subscription key.
#
# This key can be retrieved after creating a Collos account at:
# http://preview.collos.org/
request_timeout=60
